// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#pragma once

#include "djinni_support.hpp"
#include "playerMapper.hpp"

namespace djinni_generated {

class NativePlayerMapper final : ::djinni::JniInterface<::shared_objects::PlayerMapper, NativePlayerMapper> {
public:
    using CppType = std::shared_ptr<::shared_objects::PlayerMapper>;
    using CppOptType = std::shared_ptr<::shared_objects::PlayerMapper>;
    using JniType = jobject;

    using Boxed = NativePlayerMapper;

    ~NativePlayerMapper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePlayerMapper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePlayerMapper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePlayerMapper();
    friend ::djinni::JniClass<NativePlayerMapper>;
    friend ::djinni::JniInterface<::shared_objects::PlayerMapper, NativePlayerMapper>;

};

}  // namespace djinni_generated
