// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#pragma once

#include "djinni_support.hpp"
#include "player.hpp"

namespace djinni_generated {

class NativePlayer final {
public:
    using CppType = ::shared_objects::Player;
    using JniType = jobject;

    using Boxed = NativePlayer;

    ~NativePlayer();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativePlayer();
    friend ::djinni::JniClass<NativePlayer>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mobitee/shared_objects/Player") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mClubId { ::djinni::jniGetFieldID(clazz.get(), "mClubId", "Ljava/lang/String;") };
    const jfieldID field_mEmail { ::djinni::jniGetFieldID(clazz.get(), "mEmail", "Ljava/lang/String;") };
    const jfieldID field_mGender { ::djinni::jniGetFieldID(clazz.get(), "mGender", "Ljava/lang/String;") };
    const jfieldID field_mHcp { ::djinni::jniGetFieldID(clazz.get(), "mHcp", "Ljava/lang/String;") };
    const jfieldID field_mImageUrl { ::djinni::jniGetFieldID(clazz.get(), "mImageUrl", "Ljava/lang/String;") };
    const jfieldID field_mLastName { ::djinni::jniGetFieldID(clazz.get(), "mLastName", "Ljava/lang/String;") };
    const jfieldID field_mFirstName { ::djinni::jniGetFieldID(clazz.get(), "mFirstName", "Ljava/lang/String;") };
    const jfieldID field_mPhone { ::djinni::jniGetFieldID(clazz.get(), "mPhone", "Ljava/lang/String;") };
    const jfieldID field_mSlope { ::djinni::jniGetFieldID(clazz.get(), "mSlope", "Ljava/lang/String;") };
    const jfieldID field_mTs { ::djinni::jniGetFieldID(clazz.get(), "mTs", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
