// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#import "MSOPlayer.h"
#import <Foundation/Foundation.h>
@class MSOPlayerMapper;


@interface MSOPlayerMapper : NSObject

+ (nullable MSOPlayerMapper *)create;

- (nonnull MSOPlayer *)getPlayer:(nonnull NSString *)json;

@end
