// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#import <Foundation/Foundation.h>

@interface MSOPlayer : NSObject
- (nonnull instancetype)initWithClubId:(nonnull NSString *)clubId
                                 email:(nonnull NSString *)email
                                gender:(nonnull NSString *)gender
                                   hcp:(nonnull NSString *)hcp
                              imageUrl:(nonnull NSString *)imageUrl
                              lastName:(nonnull NSString *)lastName
                             firstName:(nonnull NSString *)firstName
                                 phone:(nonnull NSString *)phone
                                 slope:(nonnull NSString *)slope
                                    ts:(nonnull NSString *)ts;
+ (nonnull instancetype)playerWithClubId:(nonnull NSString *)clubId
                                   email:(nonnull NSString *)email
                                  gender:(nonnull NSString *)gender
                                     hcp:(nonnull NSString *)hcp
                                imageUrl:(nonnull NSString *)imageUrl
                                lastName:(nonnull NSString *)lastName
                               firstName:(nonnull NSString *)firstName
                                   phone:(nonnull NSString *)phone
                                   slope:(nonnull NSString *)slope
                                      ts:(nonnull NSString *)ts;

@property (nonatomic, readonly, nonnull) NSString * clubId;

@property (nonatomic, readonly, nonnull) NSString * email;

@property (nonatomic, readonly, nonnull) NSString * gender;

@property (nonatomic, readonly, nonnull) NSString * hcp;

@property (nonatomic, readonly, nonnull) NSString * imageUrl;

@property (nonatomic, readonly, nonnull) NSString * lastName;

@property (nonatomic, readonly, nonnull) NSString * firstName;

@property (nonatomic, readonly, nonnull) NSString * phone;

@property (nonatomic, readonly, nonnull) NSString * slope;

@property (nonatomic, readonly, nonnull) NSString * ts;

@end
