// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#import "MSOPlayer.h"


@implementation MSOPlayer

- (nonnull instancetype)initWithClubId:(nonnull NSString *)clubId
                                 email:(nonnull NSString *)email
                                gender:(nonnull NSString *)gender
                                   hcp:(nonnull NSString *)hcp
                              imageUrl:(nonnull NSString *)imageUrl
                              lastName:(nonnull NSString *)lastName
                             firstName:(nonnull NSString *)firstName
                                 phone:(nonnull NSString *)phone
                                 slope:(nonnull NSString *)slope
                                    ts:(nonnull NSString *)ts
{
    if (self = [super init]) {
        _clubId = [clubId copy];
        _email = [email copy];
        _gender = [gender copy];
        _hcp = [hcp copy];
        _imageUrl = [imageUrl copy];
        _lastName = [lastName copy];
        _firstName = [firstName copy];
        _phone = [phone copy];
        _slope = [slope copy];
        _ts = [ts copy];
    }
    return self;
}

+ (nonnull instancetype)playerWithClubId:(nonnull NSString *)clubId
                                   email:(nonnull NSString *)email
                                  gender:(nonnull NSString *)gender
                                     hcp:(nonnull NSString *)hcp
                                imageUrl:(nonnull NSString *)imageUrl
                                lastName:(nonnull NSString *)lastName
                               firstName:(nonnull NSString *)firstName
                                   phone:(nonnull NSString *)phone
                                   slope:(nonnull NSString *)slope
                                      ts:(nonnull NSString *)ts
{
    return [[self alloc] initWithClubId:clubId
                                  email:email
                                 gender:gender
                                    hcp:hcp
                               imageUrl:imageUrl
                               lastName:lastName
                              firstName:firstName
                                  phone:phone
                                  slope:slope
                                     ts:ts];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p clubId:%@ email:%@ gender:%@ hcp:%@ imageUrl:%@ lastName:%@ firstName:%@ phone:%@ slope:%@ ts:%@>", self.class, self, self.clubId, self.email, self.gender, self.hcp, self.imageUrl, self.lastName, self.firstName, self.phone, self.slope, self.ts];
}

@end
