// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

package com.mobitee.shared_objects;

public final class Player {


    /*package*/ final String mClubId;

    /*package*/ final String mEmail;

    /*package*/ final String mGender;

    /*package*/ final String mHcp;

    /*package*/ final String mImageUrl;

    /*package*/ final String mLastName;

    /*package*/ final String mFirstName;

    /*package*/ final String mPhone;

    /*package*/ final String mSlope;

    /*package*/ final String mTs;

    public Player(
            String clubId,
            String email,
            String gender,
            String hcp,
            String imageUrl,
            String lastName,
            String firstName,
            String phone,
            String slope,
            String ts) {
        this.mClubId = clubId;
        this.mEmail = email;
        this.mGender = gender;
        this.mHcp = hcp;
        this.mImageUrl = imageUrl;
        this.mLastName = lastName;
        this.mFirstName = firstName;
        this.mPhone = phone;
        this.mSlope = slope;
        this.mTs = ts;
    }

    public String getClubId() {
        return mClubId;
    }

    public String getEmail() {
        return mEmail;
    }

    public String getGender() {
        return mGender;
    }

    public String getHcp() {
        return mHcp;
    }

    public String getImageUrl() {
        return mImageUrl;
    }

    public String getLastName() {
        return mLastName;
    }

    public String getFirstName() {
        return mFirstName;
    }

    public String getPhone() {
        return mPhone;
    }

    public String getSlope() {
        return mSlope;
    }

    public String getTs() {
        return mTs;
    }

    @Override
    public String toString() {
        return "Player{" +
                "mClubId=" + mClubId +
                "," + "mEmail=" + mEmail +
                "," + "mGender=" + mGender +
                "," + "mHcp=" + mHcp +
                "," + "mImageUrl=" + mImageUrl +
                "," + "mLastName=" + mLastName +
                "," + "mFirstName=" + mFirstName +
                "," + "mPhone=" + mPhone +
                "," + "mSlope=" + mSlope +
                "," + "mTs=" + mTs +
        "}";
    }

}
