// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

package com.mobitee.shared_objects;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class PlayerMapper {
    public abstract Player getPlayer(String json);

    public static native PlayerMapper create();

    private static final class CppProxy extends PlayerMapper
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public Player getPlayer(String json)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getPlayer(this.nativeRef, json);
        }
        private native Player native_getPlayer(long _nativeRef, String json);
    }
}
