// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#pragma once

#include <string>
#include <utility>

namespace shared_objects {

struct Player final {
    std::string clubId;
    std::string email;
    std::string gender;
    std::string hcp;
    std::string imageUrl;
    std::string lastName;
    std::string firstName;
    std::string phone;
    std::string slope;
    std::string ts;

    Player(std::string clubId_,
           std::string email_,
           std::string gender_,
           std::string hcp_,
           std::string imageUrl_,
           std::string lastName_,
           std::string firstName_,
           std::string phone_,
           std::string slope_,
           std::string ts_)
    : clubId(std::move(clubId_))
    , email(std::move(email_))
    , gender(std::move(gender_))
    , hcp(std::move(hcp_))
    , imageUrl(std::move(imageUrl_))
    , lastName(std::move(lastName_))
    , firstName(std::move(firstName_))
    , phone(std::move(phone_))
    , slope(std::move(slope_))
    , ts(std::move(ts_))
    {}
};

}  // namespace shared_objects
