// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from general.djinni

#pragma once

#include <memory>
#include <string>

namespace shared_objects {

struct Player;

class PlayerMapper {
public:
    virtual ~PlayerMapper() {}

    static std::shared_ptr<PlayerMapper> create();

    virtual Player get_player(const std::string & json) = 0;
};

}  // namespace shared_objects
